dist: trusty
language: node_js
node_js:
  - "8"
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - hiptest-publisher -c mocha.conf --only=actionwords --test-run-id=172464
script:
  - npm test

after_script:
  - hiptest-publisher -c mocha.conf --push-format="tap" --push=output.txt --test-run-id=172464